In [53]:
from sklearn.manifold import SpectralEmbedding
import numpy as np

w1=np.array([[0,0,1,0,0],[0,0,0,0,1],[1,0,0,1,0],[0,0,1,0,0],[0,1,0,0,0]])
embedder = SpectralEmbedding(n_components=1, affinity='precomputed', n_neighbors = 1)
Xge = embedder.fit_transform(w1)
print(embedder.affinity_matrix_)
Xge

[[0 0 1 0 0]
 [0 0 0 0 1]
 [1 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]]


/Users/Alchemist/opt/anaconda3/lib/python3.7/site-packages/sklearn/manifold/spectral_embedding_.py:235: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


array([[0.49604346],
       [0.08877938],
       [0.49604346],
       [0.49604346],
       [0.08877938]])

In [55]:
w2 = np.array([[0,1,1,1,1],[1,0,0,0,1],[1,0,0,1,0],[1,0,1,0,0],[1,1,0,0,0]])
embedder2 = SpectralEmbedding(n_components=1, affinity='precomputed', n_neighbors = 2)
Xge2 = embedder2.fit_transform(w2)
print(embedder2.affinity_matrix_)
Xge2

[[0 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 1 0]
 [1 0 1 0 0]
 [1 1 0 0 0]]


array([[ 1.34355356e-16],
       [-3.53553391e-01],
       [ 3.53553391e-01],
       [ 3.53553391e-01],
       [-3.53553391e-01]])

  (0, 0)	1.0
  (0, 3)	0.5
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	0.5
  (4, 4)	1.0


/Users/Alchemist/opt/anaconda3/lib/python3.7/site-packages/sklearn/manifold/spectral_embedding_.py:235: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


array([[0.        ],
       [0.8398718 ],
       [0.53741642],
       [0.        ],
       [0.07615087]])